personas:
  male:
    default_variant: normal
    variants:
      normal:
        hi:
          params:
            hm_omega: 1.3
            am_puck: 1.0
          voice: "hm_omega"
        en:
          params:
            am_puck: 1.0
            hm_omega: 0.8
          voice: "am_puck"
      alt2:
        hi:
          params:
            hm_omega: 1.3
            am_michael: 1.0
          voice: "hm_omega"
        en:
          params:
            am_michael: 1.0
            hm_omega: 0.8
          voice: "am_michael"
      special_weird:
        any:
          voice: "pm_alex"

  female:
    default_variant: normal
    variants:
      normal:
        hi:
          params:
            hf_alpha: 1.2
            af_sky: 0.7
          voice: "hf_alpha"
        en:
          params:
            hf_alpha: 0.4
            af_sky: 1.0
          voice: "af_sky"
      alt2:
        hi:
          params:
            hf_alpha: -1.2
            af_aoede: 0.7
          voice: "hf_alpha"
        en:
          params:
            hf_alpha: 0.4
            af_aoede: 1.0
          voice: "af_aoede"
      special_weird:
        any:
          voice: "pf_dora"
      anime:
        any:
          voice: "jf_alpha"

routing:
  camera_events:
    see_blackie:
      persona: female
      variant: anime
      voice_override: "jf_alpha"
      line: "blackieee"